export const LoaderConfig = {
    Background: "src/sprites/Background.jpg",
    gameBg: "src/sprites/Background.jpg",
    spinBtn : "/src/sprites/ButtonSpin_1.png",
    spinBtnOnPressed :  "/src/sprites/ButtonSpinHover_1.png",

    autoSpin :  "/src/sprites/ButtonAutoSpin_1.png",
    autoSpinOnPressed : "/src/sprites/ButtonAutoSpinHover_1.png",
    pBtn  :  "/src/sprites/ButtonPlus.png",
    pBtnH  :  "/src/sprites/ButtonPlusHover.png",
    mBtn  :  "/src/sprites/ButtonMinus.png",
    mBtnH  :  "/src/sprites/ButtonMinusHover.png",
    lines :  "/src/sprites/LineBetButton.png",

    winPanel :  "/src/sprites/winPanel.png",

    settingBtn :  "/src/sprites/ButtonSettings.png",
    settingBtnH :  "/src/sprites/ButtonSettingsHover.png",
    infoBtn :  "/src/sprites/ButtonInfo.png",
    infoBtnH :  "/src/sprites/ButtonInfoHover.png",

    paytableIcon :"src/sprites/ButtonInfo.png", 
    balanceBox: "src/sprites/BalanceBox.png",

    on: "src/sprites/on.png",
    off: "src/sprites/off.png",

    toggleBar: "src/sprites/toggleBarBg.png",
    winLine: "src/sprites/winLine.png",

    settingPopup: "src/sprites/settingsPopupBg.png",
    musicText: "src/sprites/MusicText.png",
    soundsText: "src/sprites/SoundsText.png",
    settingHeading: "src/sprites/settingsHeading.png",
    bottomLayer: "src/sprites/bottomLayer.png",
    boxPanel: "src/sprites/box.png",
    insideLine: "src/sprites/insideLine.png",
    stopClose: "src/sprites/stopClose.png",
    cowbg:"src/sprites/cowbg.png",
    threeCow: "src/sprites/threeWildCows.png",
    jackpotBg:"src/sprites/jackpotBg.png",

    exitButton: "src/sprites/ExitButton.png",
    exitButtonPressed: "src/sprites/ExitButton.png",

    messagePopup: "src/sprites/messagePopup.png",
    leftArrow: "src/sprites/leftArrow.png",
    rightArrow: "src/sprites/RightArrow.png",
    infoCross: "src/sprites/infoCross.png",
    infoCrossPressed: "src/sprites/infoCrossPressed.png",
    disconnectClose: "src/sprites/closeButton.png",
    payLines: "src/sprites/payLines.png",

    reelBg: "src/sprites/reelBackground.png",
    leftColumn: "src/sprites/left.png",
    rightColumn: "src/sprites/right.png",

    yesButton:"src/sprites/yesButton.png",
    yesButtonHover: "src/sprites/yesButtonHover.png",
    noButton:"src/sprites/noButton.png",
    noButtonHover:"src/sprites/noButtonHover.png",
    laser: "src/sprites/laserImage.png",
    iconBg: "src/sprites/iconBg.png",
    freeSpinReel: "src/sprites/freeSpinReel.png",
    freeSpinBg: "src/sprites/freeSpinBg.jpg",


    ufo0: "src/sprites/UFO-0.png",
    ufo1: "src/sprites/UFO-1.png",
    ufo2: "src/sprites/UFO-2.png",
    ufo3: "src/sprites/UFO-3.png",
    ufo4: "src/sprites/UFO-4.png",
    ufo5: "src/sprites/UFO-5.png",
    ufo6: "src/sprites/UFO-6.png",
    ufo7: "src/sprites/UFO-7.png",
    ufo8: "src/sprites/UFO-8.png",
    ufo9: "src/sprites/UFO-9.png",
    ufo10: "src/sprites/UFO-10.png",
    ufo11: "src/sprites/UFO-11.png",
    ufo12: "src/sprites/UFO-12.png",
    ufo13: "src/sprites/UFO-13.png",
    ufo14: "src/sprites/UFO-14.png",
    ufo15: "src/sprites/UFO-15.png",


    blackCow12_0: "src/sprites/blackCow-0.png",
    blackCow12_1: "src/sprites/blackCow-1.png",
    blackCow12_2: "src/sprites/blackCow-2.png",
    blackCow12_3: "src/sprites/blackCow-3.png",
    blackCow12_4: "src/sprites/blackCow-4.png",
    blackCow12_5: "src/sprites/blackCow-5.png",
    blackCow12_6: "src/sprites/blackCow-6.png",
    blackCow12_7: "src/sprites/blackCow-7.png",
    blackCow12_8: "src/sprites/blackCow-8.png",
    blackCow12_9: "src/sprites/blackCow-9.png",
    blackCow12_10: "src/sprites/blackCow-10.png",


    brownCow12_0: "src/sprites/brownCow-0.png",
    brownCow12_1: "src/sprites/brownCow-1.png",
    brownCow12_2: "src/sprites/brownCow-2.png",
    brownCow12_3: "src/sprites/brownCow-3.png",
    brownCow12_4: "src/sprites/brownCow-4.png",
    brownCow12_5: "src/sprites/brownCow-5.png",
    brownCow12_6: "src/sprites/brownCow-6.png",
    brownCow12_7: "src/sprites/brownCow-7.png",
    brownCow12_8: "src/sprites/brownCow-8.png",
    brownCow12_9: "src/sprites/brownCow-9.png",
    brownCow12_10: "src/sprites/brownCow-10.png",

    whiteCow12_0: "src/sprites/whiteCow-0.png",
    whiteCow12_1: "src/sprites/whiteCow-1.png",
    whiteCow12_2: "src/sprites/whiteCow-2.png",
    whiteCow12_3: "src/sprites/whiteCow-3.png",
    whiteCow12_4: "src/sprites/whiteCow-4.png",
    whiteCow12_5: "src/sprites/whiteCow-5.png",
    whiteCow12_6: "src/sprites/whiteCow-6.png",
    whiteCow12_7: "src/sprites/whiteCow-7.png",
    whiteCow12_8: "src/sprites/whiteCow-8.png",
    whiteCow12_9: "src/sprites/whiteCow-9.png",
    whiteCow12_10: "src/sprites/whiteCow-10.png",

    pullAnim0: "src/sprites/Comp0.png",
    pullAnim1: "src/sprites/Comp1.png",
    pullAnim2: "src/sprites/Comp2.png",
    pullAnim3: "src/sprites/Comp3.png",
    pullAnim4: "src/sprites/Comp4.png",
    pullAnim5: "src/sprites/Comp5.png",
    pullAnim6: "src/sprites/Comp6.png",
    pullAnim7: "src/sprites/Comp7.png",
    pullAnim8: "src/sprites/Comp8.png",
    pullAnim9: "src/sprites/Comp9.png",
    pullAnim10: "src/sprites/Comp10.png",
    pullAnim11: "src/sprites/Comp11.png",
    pullAnim12: "src/sprites/Comp12.png",
    pullAnim13: "src/sprites/Comp13.png",
    pullAnim14: "src/sprites/Comp14.png",
    pullAnim15: "src/sprites/Comp15.png",
    pullAnim16: "src/sprites/Comp16.png",
    pullAnim17: "src/sprites/Comp17.png",


    cow1_0: "src/sprites/cow1-0.png",
    cow1_1: "src/sprites/cow1-1.png",
    cow1_2: "src/sprites/cow1-2.png",
    cow1_3: "src/sprites/cow1-3.png",
    cow1_4: "src/sprites/cow1-4.png",

    cow2_0: "src/sprites/cow2-0.png",
    cow2_1: "src/sprites/cow2-1.png",
    cow2_2: "src/sprites/cow2-2.png",
    cow2_3: "src/sprites/cow2-3.png",
    cow2_4: "src/sprites/cow2-4.png",
    cow2_5: "src/sprites/cow2-5.png",

    cow3_0: "src/sprites/cow3-0.png",
    cow3_1: "src/sprites/cow3-1.png",
    cow3_2: "src/sprites/cow3-2.png",
    cow3_3: "src/sprites/cow3-3.png",
    cow3_4: "src/sprites/cow3-4.png",
    cow3_5: "src/sprites/cow3-5.png",

    cow4_0: "src/sprites/cow4-0.png",
    cow4_1: "src/sprites/cow4-1.png",
    cow4_2: "src/sprites/cow4-2.png",
    cow4_3: "src/sprites/cow4-3.png",
    cow4_4: "src/sprites/cow4-4.png",

    cow5_0: "src/sprites/cow5-0.png",
    cow5_1: "src/sprites/cow5-1.png",
    cow5_2: "src/sprites/cow5-2.png",
    cow5_3: "src/sprites/cow5-3.png",
    cow5_4: "src/sprites/cow5-4.png",
    cow5_5: "src/sprites/cow5-5.png",

    slots0_0 :  "/src/sprites/Symbols/icon1/icon1.png",
    slots1_0 :  "/src/sprites/Symbols/icon2/icon2.png",
    slots2_0 :  "/src/sprites/Symbols/icon3/icon3.png",
    slots3_0 :  "/src/sprites/Symbols/icon4/icon4.png",
    slots4_0 :  "/src/sprites/Symbols/icon5/icon5.png",
    slots5_0 :  "/src/sprites/Symbols/icon6/icon6.png",
    slots6_0 :  "/src/sprites/Symbols/icon7/icon7.png",
    slots7_0 :  "/src/sprites/Symbols/icon8/icon8.png",
    slots8_0 :  "/src/sprites/Symbols/icon9/icon9.png",
    slots9_0 :  "/src/sprites/Symbols/icon10/icon10.png",
    slots10_0 :  "/src/sprites/Symbols/icon11/icon11.png",
    slots11_0 :  "/src/sprites/Symbols/icon12/icon12.png",
    slots12_0 :  "/src/sprites/Symbols/icon13/icon12.png",
    slots13_0 :  "/src/sprites/Symbols/icon14/icon14.png",

    blast_0: "src/sprites/blast-0.png",
    blast_1: "src/sprites/blast-1.png",
    blast_2: "src/sprites/blast-2.png",
    blast_3: "src/sprites/blast-3.png",
    blast_4: "src/sprites/blast-4.png",
    blast_5: "src/sprites/blast-5.png",
    blast_6: "src/sprites/blast-6.png",
    blast_7: "src/sprites/blast-7.png",
    blast_8: "src/sprites/blast-8.png",
    blast_9: "src/sprites/blast-9.png",
    blast_10: "src/sprites/blast-10.png",
    blast_11: "src/sprites/blast-11.png",
    blast_12: "src/sprites/blast-12.png",
    blast_13: "src/sprites/blast-13.png",
    blast_14: "src/sprites/blast-14.png",
}

export const staticData = {
    Background:  "src/sprites/Background.jpg",
};

export const fontData = {
    Anton : "src/fonts/Anton-Regular.ttf"
}

export const LoaderSoundConfig: any = {
        backgroundMusic: "src/sounds/bgmusic.mp3",
        onSpin :  "/src/sounds/slot-machine-loop.mp3",
        spinButton: "src/sounds/SpinButton.mp3",
        winMusic: "src/sounds/win.wav",
        buttonpressed: "src/sounds/button.wav",
        laserSound: "src/sounds/laser.wav",
        blastSound: "src/sounds/bomb.wav",
        pullSound: "src/sounds/pull.wav"

};
