export const LoaderConfig = {
    Background: "src/sprites/Background.jpg",
    gameBg: "src/sprites/Background.jpg",
    spinBtn : "/src/sprites/ButtonSpin_1.png",
    spinBtnOnPressed :  "/src/sprites/ButtonSpinHover_1.png",
    maxBetBtn :  "/src/sprites/ButtonMaxBet_1.png",
    maxBetBtOnPressed :  "/src/sprites/ButtonMaxBetHover.png",
    autoSpin :  "/src/sprites/ButtonAutoSpin_1.png",
    autoSpinOnPressed : "/src/sprites/ButtonAutoSpinHover_1.png",
    pBtn  :  "/src/sprites/ButtonPlus.png",
    pBtnH  :  "/src/sprites/ButtonPlusHover.png",
    mBtn  :  "/src/sprites/ButtonMinus.png",
    mBtnH  :  "/src/sprites/ButtonMinusHover.png",
    lines :  "/src/sprites/LineBetButton.png",
    // GambleBg: "src/sprites/GambleBg.png",
    // winPanel :  "/src/sprites/PanelWin.png",
    // winPanel1:  "/src/sprites/PanelWin1.png",  
    // bonusLogo: "src/sprites/BonusLogo.png",
    // riskLogo: "src/sprites/RiskLogo.png",      
    balancePanel :  "/src/sprites/PanelBalance.png",
    winPanel :  "/src/sprites/winPanel.png",
    // doubleButton: "src/sprites/doubleButton.png",
    doubleButtonPressed : "src/sprites/doubleButtonPressed.png",
    MenuBtn :  "/src/sprites/ButtonMenu.png",
    MenuBtnH :  "/src/sprites/ButtonMenuHover.png",
    settingBtn :  "/src/sprites/ButtonSettings.png",
    settingBtnH :  "/src/sprites/ButtonSettingsHover.png",
    infoBtn :  "/src/sprites/ButtonInfo.png",
    infoBtnH :  "/src/sprites/ButtonInfoHover.png",
    linesNumber: "src/sprites/buttonBg.png",
    lineBox: "src/sprites/LineBox.png",
    paytableIcon :"src/sprites/ButtonInfo.png", 
    balanceBox: "src/sprites/BalanceBox.png",
    balanceText: "src/sprites/BalanceText.png",
    settingText: "src/sprites/SettingsText.png",
    rightPin: "src/sprites/rightPin.png",
    leftPin: "src/sprites/leftPin.png",
    on: "src/sprites/on.png",
    off: "src/sprites/off.png",
    onButton: "src/sprites/toggleOn.png",
    offButton: "src/sprites/toggleOff.png",
    toggleBar: "src/sprites/toggleBarBg.png",
    winLine: "src/sprites/winLine.png",
    yourWin: "src/sprites/YourWin.png",

    settingPopup: "src/sprites/settingsPopupBg.png",
    musicText: "src/sprites/MusicText.png",
    soundsText: "src/sprites/SoundsText.png",
    settingHeading: "src/sprites/settingsHeading.png",
    bottomLayer: "src/sprites/bottomLayer.png",
    boxPanel: "src/sprites/box.png",
    insideLine: "src/sprites/insideLine.png",


    number0: "src/sprites/number1.png",
    number1: "src/sprites/number2.png",
    number2: "src/sprites/number3.png",
    number3: "src/sprites/number4.png",
    number4: "src/sprites/number5.png",
    number5: "src/sprites/number6.png",
    number6: "src/sprites/number7.png",
    number7: "src/sprites/number8.png",
    number8: "src/sprites/number9.png",
    number9: "src/sprites/number10.png",
    number10: "src/sprites/number11.png",
    number11: "src/sprites/number12.png",

    box0: "src/sprites/box0.png",
    box1: "src/sprites/box1.png",
    box2: "src/sprites/box2.png",
    box3: "src/sprites/box3.png",
    box4: "src/sprites/box4.png",
    box5: "src/sprites/box5.png",

    inofIcon1: "src/sprites/info1.png",
    inofIcon2: "src/sprites/info2.png",
    inofIcon3: "src/sprites/info3.png",
    inofIcon4: "src/sprites/info4.png",
    inofIcon5: "src/sprites/info5.png",
    inofIcon6: "src/sprites/info6.png",
    inofIcon7: "src/sprites/info7.png",
    inofIcon8: "src/sprites/info8.png",
    inofIcon9: "src/sprites/info9.png",
    inofIcon10: "src/sprites/info10.png",
    inofIcon11: "src/sprites/info11.png",

    exitButton: "src/sprites/ExitButton.png",
    exitButtonPressed: "src/sprites/ExitButton.png",

    messagePopup: "src/sprites/messagePopup.png",
    leftArrow: "src/sprites/leftArrow.png",
    rightArrow: "src/sprites/RightArrow.png",
    infoCross: "src/sprites/infoCross.png",
    infoCrossPressed: "src/sprites/infoCrossPressed.png",
    disconnectClose: "src/sprites/closeButton.png",
    BonusScenegame: "src/sprites/BonusSceneImage.jpg",
    dollar: 'src/sprites/dollarSign.png',
    payLines: "src/sprites/payLines.png",

    reelBg: "src/sprites/reelBackground.png",
    leftColumn: "src/sprites/left.png",
    rightColumn: "src/sprites/right.png",
    topColumn: "src/sprites/top.png",
    middleLine: "src/sprites/middleBars.png",
    gameLogo: "src/sprites/gameLogo.png",
    buttonBg: "src/sprites/buttonBg.png",
    totalBetText: "src/sprites/totalBetText.png",
    winText: "src/sprites/winText.png",
    megaWinText: "src/sprites/MegaWin.png",
    hugeWinText: "src/sprites/hugeWin.png",
    bigWinText: "src/sprites/BigWinText.png",
    jackpotText: "src/sprites/jackpotText.png",
    leftWinColumn: "src/sprites/woodenStick.png",
    rightWinColumn: "src/sprites/woodenStick.png",
    winPanelBalance: "src/sprites/biggerPanel.png",
    rightCoin: "src/sprites/rightCoin.png",
    leftCoin: "src/sprites/leftCoin.png",

 
    soundImage:"src/sprites/Sounds.png",
    musicImage: "src/sprites/Music.png",
    yesButton:"src/sprites/yesButton.png",
    yesButtonHover: "src/sprites/yesButtonHover.png",
    noButton:"src/sprites/noButton.png",
    noButtonHover:"src/sprites/noButtonHover.png",
    sounProgress: "src/sprites/soundProgreesBar.png",
    // soundIndicator: "src/sprites/Indicator.png",
    // indicatorSprite: "src/sprites/SliderButton.png",

    slots0_0 :  "/src/sprites/Symbols/icon1/icon1.png",
    slots1_0 :  "/src/sprites/Symbols/icon2/icon2.png",
    slots2_0 :  "/src/sprites/Symbols/icon3/icon3.png",
    slots3_0 :  "/src/sprites/Symbols/icon4/icon4.png",
    slots4_0 :  "/src/sprites/Symbols/icon5/icon5.png",
    slots5_0 :  "/src/sprites/Symbols/icon6/icon6.png",
    slots6_0 :  "/src/sprites/Symbols/icon7/icon7.png",
    slots7_0 :  "/src/sprites/Symbols/icon8/icon8.png",
    slots8_0 :  "/src/sprites/Symbols/icon9/icon9.png",
    slots9_0 :  "/src/sprites/Symbols/icon10/icon10.png",
    slots10_0 :  "/src/sprites/Symbols/icon11/icon11.png",
    slots11_0 :  "/src/sprites/Symbols/icon12/icon12.png",
    slots12_0 :  "/src/sprites/Symbols/icon13/icon12.png",
    slots13_0 :  "/src/sprites/Symbols/icon14/icon14.png",

    blast_0: "src/sprites/blast-0.png",
    blast_1: "src/sprites/blast-1.png",
    blast_2: "src/sprites/blast-2.png",
    blast_3: "src/sprites/blast-3.png",
    blast_4: "src/sprites/blast-4.png",
    blast_5: "src/sprites/blast-5.png",
    blast_6: "src/sprites/blast-6.png",
    blast_7: "src/sprites/blast-7.png",
    blast_8: "src/sprites/blast-8.png",
    blast_9: "src/sprites/blast-9.png",
    blast_10: "src/sprites/blast-10.png",
    blast_11: "src/sprites/blast-11.png",
    blast_12: "src/sprites/blast-12.png",
    blast_13: "src/sprites/blast-13.png",
    blast_14: "src/sprites/blast-14.png",
    



    winning0: "src/sprites/winning87.png",
    winning1: "src/sprites/winning88.png",
    winning2: "src/sprites/winning89.png",
    winning3: "src/sprites/winning90.png",
    winning4: "src/sprites/winning91.png",
    winning5: "src/sprites/winning92.png",
    winning6: "src/sprites/winning93.png",
    winning7: "src/sprites/winning94.png",
    winning8: "src/sprites/winning95.png",
    winning9: "src/sprites/winning96.png",
    winning10: "src/sprites/winning97.png",
    winning11: "src/sprites/winning98.png",
    winning12: "src/sprites/winning99.png",
    winning13: "src/sprites/winning100.png",
    winning14: "src/sprites/winning101.png",
    winning15: "src/sprites/winning102.png",
    winning16: "src/sprites/winning103.png",
    winning17: "src/sprites/winning104.png",
    winning18: "src/sprites/winning105.png",
    winning19: "src/sprites/winning106.png",
    winning20: "src/sprites/winning107.png",
    winning21: "src/sprites/winning108.png",
    winning22: "src/sprites/winning109.png",
    winning23: "src/sprites/winning110.png",
    winning24: "src/sprites/winning111.png",
    winning25: "src/sprites/winning112.png",
    winning26: "src/sprites/winning113.png",
    winning27: "src/sprites/winning114.png",
    winning28: "src/sprites/winning115.png",
    winning29: "src/sprites/winning116.png",
    winning30: "src/sprites/winning117.png",
    winning31: "src/sprites/winning118.png",
    winning32: "src/sprites/winning119.png",
    winning33: "src/sprites/winning120.png",
    winning34: "src/sprites/winning121.png",
    winning35: "src/sprites/winning122.png",
    winning36: "src/sprites/winning123.png",
    winning37: "src/sprites/winning124.png",
    winning38: "src/sprites/winning125.png",
    winning39: "src/sprites/winning126.png",
    winning40: "src/sprites/winning127.png",
    winning41: "src/sprites/winning128.png",
    winning42: "src/sprites/winning129.png",
    winning43: "src/sprites/winning130.png",
    winning44: "src/sprites/winning131.png",
    winning45: "src/sprites/winning132.png",
    winning46: "src/sprites/winning133.png",
    winning47: "src/sprites/winning134.png",
    winning48: "src/sprites/winning135.png",
    winning49: "src/sprites/winning136.png",
}

export const staticData = {
    Background:  "src/sprites/Background.jpg",
};

export const fontData = {
    Anton : "src/fonts/Anton-Regular.ttf"
}

export const LoaderSoundConfig: any = {
        backgroundMusic: "src/sounds/bgmusic.mp3",
        onSpin :  "/src/sounds/slot-machine-loop.mp3",
        spinButton: "src/sounds/SpinButton.wav",
        winMusic: "src/sounds/win.wav",
        buttonpressed: "src/sounds/button.mp3",
        bonusBg: "src/sounds/bonusbg.mp3",
        bonuswin: "src/sounds/bonuswin.mp3",
        bonusboxOpen: "src/sounds/chestopen.wav"
};
